logging:
  level:
    org:
      hibernate:
        SQL: debug
spring:
  datasource:
    url: '@dataSource.url@'
    username: '@dataSource.user@'
    password: '@dataSource.password@'
    max-active: 4
    max-idle: 2
    max-wait: 10000
    remove-abandoned: true
    remove-abandoned-timeout: 60
    log-abandoned: true
    validation-query: SELECT 1
  devtools:
    restart:
      trigger-file: reload
    livereload:
      enabled: false
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      format-sql: true
      use-sql-comments: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mail:
    host: smtp.office365.com
    port: 587
    username: '@email.address@'
    password: '@email.password@'
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
project:
  jwt:
    signKey: '@jwt.signKey@'
    expirationMinutes: 1440
file:
  base-path: "./"

server:
  port: 8080
